/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FileConverterRouteImport } from './routes/file-converter'
import { Route as GradientRouteImport } from './routes/gradient'
import { Route as PasswordRouteImport } from './routes/password'
import { Route as QrCodeRouteImport } from './routes/qr-code'
import { Route as TimezoneRouteImport } from './routes/timezone'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FileConverterRoute = FileConverterRouteImport.update({
  id: '/file-converter',
  path: '/file-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const GradientRoute = GradientRouteImport.update({
  id: '/gradient',
  path: '/gradient',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRoute = PasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeRoute = QrCodeRouteImport.update({
  id: '/qr-code',
  path: '/qr-code',
  getParentRoute: () => rootRouteImport,
} as any)
const TimezoneRoute = TimezoneRouteImport.update({
  id: '/timezone',
  path: '/timezone',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/file-converter': typeof FileConverterRoute
  '/gradient': typeof GradientRoute
  '/password': typeof PasswordRoute
  '/qr-code': typeof QrCodeRoute
  '/timezone': typeof TimezoneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/file-converter': typeof FileConverterRoute
  '/gradient': typeof GradientRoute
  '/password': typeof PasswordRoute
  '/qr-code': typeof QrCodeRoute
  '/timezone': typeof TimezoneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/file-converter': typeof FileConverterRoute
  '/gradient': typeof GradientRoute
  '/password': typeof PasswordRoute
  '/qr-code': typeof QrCodeRoute
  '/timezone': typeof TimezoneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/file-converter'
    | '/gradient'
    | '/password'
    | '/qr-code'
    | '/timezone'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/file-converter'
    | '/gradient'
    | '/password'
    | '/qr-code'
    | '/timezone'
  id:
    | '__root__'
    | '/'
    | '/file-converter'
    | '/gradient'
    | '/password'
    | '/qr-code'
    | '/timezone'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FileConverterRoute: typeof FileConverterRoute
  GradientRoute: typeof GradientRoute
  PasswordRoute: typeof PasswordRoute
  QrCodeRoute: typeof QrCodeRoute
  TimezoneRoute: typeof TimezoneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-converter': {
      id: '/file-converter'
      path: '/file-converter'
      fullPath: '/file-converter'
      preLoaderRoute: typeof FileConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gradient': {
      id: '/gradient'
      path: '/gradient'
      fullPath: '/gradient'
      preLoaderRoute: typeof GradientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code': {
      id: '/qr-code'
      path: '/qr-code'
      fullPath: '/qr-code'
      preLoaderRoute: typeof QrCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timezone': {
      id: '/timezone'
      path: '/timezone'
      fullPath: '/timezone'
      preLoaderRoute: typeof TimezoneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FileConverterRoute: FileConverterRoute,
  GradientRoute: GradientRoute,
  PasswordRoute: PasswordRoute,
  QrCodeRoute: QrCodeRoute,
  TimezoneRoute: TimezoneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
